//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ember_Medical_Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int id { get; set; }
        public Nullable<int> Receptionist_id { get; set; }
        public Nullable<int> Bill_id { get; set; }
        public Nullable<int> Patient_id { get; set; }
        public string Pay_Status { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Receptionist Receptionist { get; set; }
    }
}
