//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ember_Medical_Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public Nullable<int> Receptionist_id { get; set; }
        public Nullable<int> Patient_id { get; set; }
        public Nullable<int> Nurse_id { get; set; }
        public float Weight_lb { get; set; }
        public float Height_cm { get; set; }
        public string Blood_Pressure { get; set; }
        public string Blood_Sugar { get; set; }
        public Nullable<int> Physician_id { get; set; }
        public string Symptoms { get; set; }
        public string Diagnosis { get; set; }
        public string Prescription { get; set; }
        public string Comments { get; set; }
    
        public virtual Nurse Nurse { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Physician Physician { get; set; }
        public virtual Receptionist Receptionist { get; set; }
    }
}
